### ISSUE TITLE
Error message for create_metadata

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1265]
I tried to create the metadata file for the Swadesh-1961-100 list, but when running `concepticon create_metadata`, I got the following error message:

```
Traceback (most recent call last):
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/bin/concepticon", line 8, in <module>
    sys.exit(main())
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/pyconcepticon/__main__.py", line 62, in main
    return args.main(args) or 0
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/pyconcepticon/commands/create_metadata.py", line 12, in run
    for col in cl.metadata.tableSchema.columns:
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/pyconcepticon/models.py", line 234, in metadata
    return self.tg.tables[0]
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/pyconcepticon/models.py", line 226, in tg
    tg = TableGroup.from_file(md)
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/csvw/metadata.py", line 1039, in from_file
    res = cls.fromvalue(data or get_json(fname))
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/csvw/metadata.py", line 430, in fromvalue
    return cls(**cls.partition_properties(d))
  File "<attrs generated init csvw.metadata.TableGroup>", line 39, in __init__
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/csvw/metadata.py", line 1402, in converter_tables
    res.append(Table.fromvalue(vv) if isinstance(vv, dict) else vv)
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/csvw/metadata.py", line 430, in fromvalue
    return cls(**cls.partition_properties(d))
  File "<attrs generated init csvw.metadata.Table>", line 46, in __init__
  File "/Users/mathildavanzantwijk/CALC/virtualenv/new-env/lib/python3.10/site-packages/csvw/metadata.py", line 1166, in __attrs_post_init__
    raise ValueError('url property is required for Tables')
ValueError: url property is required for Tables
```

@xrotwang, can you maybe help to find the issue?

**Comment by xrotwang** [comment]
Ah, `csvw>=3` is a bit more picky. So downgrading via `pip install csvw<3` may be the quickest solution for now.

**Comment by xrotwang** [comment]
Alternatively, try upgrading `pyconcepticon`: `pip install -U pyconcepticon`.

**Comment by mathildavz** [comment]
It seems to have worked, thank you! @xrotwang
